version: "3.7"
services:
    ## PostGre Docker Compose Config
    postgres-order:
        container_name: meta-analyzer-container
        image: postgres
        environment:
            POSTGRES_DB: meta-analyzer-db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /data/postgres
        volumes:
            - ./meta-analyzer-db:/data/postgres
        expose:
            - "5432"
        ports:
            - "5432:5432"
        command: -p 5432
        restart: always
